### ISSUE TITLE
ReCaptcha not visible and in console log grecaptcha.render is not a function

### ISSUE THREAD

**Issue by nagendra-kodi** [magespecialist/m2-MSP_ReCaptcha#36]
### Preconditions

1. Magento version 2.1.7
2. PHP Version 7.0.30

### Steps to reproduce

1. when i browse directly customer account creation page https://example.com/customer/account/create/ captcha is not loading for the first time (or) Load the customer account creation page in the In-private window.
2. Console log ERROR:
/vendor/msp/recaptcha/view/frontend/web/js/reCaptcha.js
```
reCaptcha.js:127 Uncaught TypeError: grecaptcha.render is not a function
    at UiClass.initCaptcha (reCaptcha.js:127)
    at reCaptcha.js:175 
```

### Expected result

1. Need to Load google recaptcha.
2. No errors in console log related to recaptcha.

### Actual result

![msp-recaptcha error](https://user-images.githubusercontent.com/28343427/43771910-39fe62e6-9a5e-11e8-83fa-50e4c646968d.png)

- When i refresh a page captcha is loading.
- When i browse from Home page -> sign in page -> Create account page in this way their is no errors and captcha is loading.

**Comment by pmclain** [comment]
It looks like a race condition introduced here https://github.com/magespecialist/m2-MSP_ReCaptcha/blob/master/view/frontend/web/js/reCaptcha.js#L139-L144 not sure what a proper fix would be.

**Comment by pmclain** [comment]
```
diff --git a/view/frontend/web/js/reCaptcha.js b/view/frontend/web/js/reCaptcha.js
index 09b3247..28ec9e2 100644
--- a/view/frontend/web/js/reCaptcha.js
+++ b/view/frontend/web/js/reCaptcha.js
@@ -137,7 +137,7 @@ define(
 
                 if (this.getIsVisible()) {
                     var initCaptchaInterval = setInterval(function () {
-                        if (window.grecaptcha) {
+                        if (window.grecaptcha && window.grecaptcha.render) {
                             clearInterval(initCaptchaInterval);
                             me.initCaptcha();
                         }
```

This seems to be working as a temporary fix.

**Comment by phoenix128** [comment]
Sorry gentlemen,
it is our fault because we are in late in deleting this repo. ReCaptcha and 2FA are oficially moved into the Magento2 github as part of 2.3 and as optional modules for 2.1 and 2.2.
You will find there the new 1.5.0 version that should fix this issue.

https://github.com/magento/magespecialist_ReCaptcha

**Comment by mattkrupnik** [comment]
@phoenix128 r u able to look on it yet, Not sure that in this 2.3 version of Magento it is fixed. Also sometimes I get error ‘recaptcha placeholder should be element or id’ I saw that it is solved in this module but some times I get this error. Thanks

**Comment by dccampbell** [comment]
@phoenix128 I installed this via the Magento repo and the issue still exists there. Their first and only version they have is `2.0.0`. I also confirmed no such fix exists in either of that repo's branches that contain code.

**Comment by phoenix128** [comment]
@dccampbell , this is definitely weird. We are checking it to fix it ASAP.
Thanks.

**Comment by phoenix128** [comment]
@dccampbell , you are totally right and your patch is working.
If you want, you can make a PR in https://github.com/magento/magespecialist_ReCaptcha so you will keep the name on it.

**Comment by dccampbell** [comment]
@phoenix128 I don't really mind either way. Which branch should the PR be against?

**Comment by phoenix128** [comment]
2.3-develop + backport from 2.2-develop and 2.0.0 .
If you have no time I can do it for you anyway.

**Comment by dccampbell** [comment]
@phoenix128 We'll need a new version tagged before the fix becomes available via composer. Any idea what the release plans are like for the new repo? Do I need to do a PR for the 2.0.0 branch as well to get that rolling? 2.2-develop is empty.

**Comment by phoenix128** [comment]
Hi @dccampbell ,
I know, I am incontact with the Magento guys because we can apply a better solution.
I am sorry for making you wait, but in august is always hard to something quickly :)

**Comment by insanityfarm** [comment]
I was able to use Magento's [recommended patching process](https://support.magento.com/hc/en-us/articles/360005484154) to apply @pmclain's fix to a 2.2.5 site. If you're in need of an immediate solution this is what I would suggest.

**Comment by dccampbell** [comment]
@phoenix128 No problem, completely understand. Don't mean to rush ya, I'm just planning around things.

@insanityfarm Thanks for that, I had completely forgotten all about that method. Much cleaner than what I was thinking. It even worked just referencing [my commit itself](https://github.com/magento/magespecialist_ReCaptcha/commit/8d8c464.diff), so no extra files to commit. :+1:

**Comment by phoenix128** [comment]
Ok, we slightly changed the fix approach and we relased a new version in the tagline.
It will be soon available in `composer` with version `2.0.1`.

https://github.com/magento/magespecialist_ReCaptcha/tree/v2.0.1 .

Thank you everybody for helping fixing this problem.
